backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'articles'
    label: 'Статьи'
    folder: 'content/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Содержание', name: 'body', widget: 'markdown' } 